site_name: Estudo API Management
site_description: Documentação de estudos sobre API Management
site_author: Fabio

theme:
  name: material
  language: pt-BR
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Modo escuro
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Modo claro
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Módulo 1 — Fundamentos: modulo-1-fundamentos/index.md
  - Módulo 2 — Ciclo de Vida de APIs: modulo-2-ciclo-de-vida/index.md
  - Módulo 3 — Governança de APIs: modulo-3-governanca/index.md
  - Módulo 4 — ITIL & APIs: modulo-4-itil/index.md
  - Módulo 5 — Segurança de APIs: modulo-5-seguranca/index.md
  - Módulo 6 — Maturidade de APIs: modulo-6-maturidade/index.md
  - Módulo 7 — Ferramentas & Padrões: modulo-7-ferramentas/index.md
